# Generated by Django 5.2.8 on 2025-11-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=models.CharField(default='', max_length=255, verbose_name='Discord ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
