# Generated by Django 5.2.8 on 2025-11-29 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_discord_id_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام روی کارت')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت')),
                ('shaba_number', models.CharField(blank=True, max_length=26, null=True, verbose_name='شماره شبا')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
