# Generated by Django 5.2.8 on 2025-12-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activation_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
