# Generated by Django 5.2.8 on 2025-11-27 07:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('enable', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('timeplay', models.PositiveIntegerField()),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comments', models.ManyToManyField(to='core.comment')),
                ('expansions', models.ManyToManyField(to='core.expansion')),
                ('methods', models.ManyToManyField(to='core.method')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('buyer', models.CharField(max_length=255, verbose_name='Buyer')),
                ('faction', models.CharField(choices=[('horde', 'Horde'), ('alliance', 'Alliance')], max_length=255, verbose_name='Faction')),
                ('region', models.CharField(choices=[('eu', 'EU'), ('us', 'US')], max_length=255, verbose_name='Region')),
                ('min_reserve', models.IntegerField(verbose_name='Min. Reserve')),
                ('price_per_1k', models.IntegerField(verbose_name='Price per 1k')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('status', models.CharField(choices=[('available', 'در دسترس'), ('Done', 'به اتمام رسیده'), ('cansel', 'لغو شده'), ('pending', 'در حال بررسی')], max_length=255, verbose_name='Status')),
                ('rest', models.IntegerField(default=0, verbose_name='Rest')),
                ('expansion', models.ManyToManyField(to='core.expansion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('realm', models.ManyToManyField(to='core.realm')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_1k', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار تکمیل'), ('review', 'در انتظار بررسی'), ('Awaiting_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('nptapprove', 'تایید نشد')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proof', models.FileField(blank=True, null=True, upload_to='proofs/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.order')),
            ],
        ),
    ]
