# Generated by Django 5.2.8 on 2025-11-27 11:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_coach_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to=core.models._get_avatar_upload_path),
        ),
    ]
