# Generated by Django 5.2.8 on 2025-11-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_offer_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
