# Generated by Django 5.2.8 on 2025-11-30 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='comments',
        ),
    ]
