# Generated by Django 5.2.8 on 2025-12-10 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_comment_coach_alter_comment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyGold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('faction', models.CharField(choices=[('horde', 'Horde'), ('alliance', 'Alliance')], max_length=255, verbose_name='Faction')),
                ('region', models.CharField(choices=[('eu', 'EU'), ('us', 'US')], max_length=255, verbose_name='Region')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('expansion', models.ManyToManyField(to='core.expansion')),
                ('realm', models.ManyToManyField(to='core.realm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
