# Generated by Django 5.2.8 on 2025-12-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_buygold'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
