# Generated by Django 5.2.8 on 2025-12-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_coach_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastsell',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
