# Generated by Django 5.2.8 on 2025-11-30 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='address',
            new_name='battle_tag',
        ),
    ]
