# Generated by Django 5.2.8 on 2025-11-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_address_invoice_battle_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='uuid',
        ),
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.ManyToManyField(to='shop.comment'),
        ),
    ]
