# Generated by Django 5.2.8 on 2025-12-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shopcomment_delete_comment_alter_product_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
