# Generated by Django 5.2.8 on 2025-12-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_delete_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
