# Generated by Django 5.2.8 on 2025-12-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_comments_shopcomment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('درانتظار پرداخت', 'Pending'), ('پرداخت ناموفق', 'Error'), ('پرداخت شده', 'Done')], default='درانتظار پرداخت', max_length=20),
        ),
    ]
