# Generated by Django 5.2.8 on 2025-12-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('error', 'پرداخت ناموفق'), ('done', 'پرداخت موفق')], default='pending', max_length=20),
        ),
    ]
